services:
  backend:
    image: tf_01/f5mobile-dashboard:latest
    env_file:
      - .env
    ports:
      - 3000:3000
    command:
      [
        "uvicorn",
        "main:app",
        "--port",
        "3000",
        "--host",
        "0.0.0.0"
      ]
